import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/component/common/Header";
import Footer from "@/component/common/Footer";
import { Providers } from "@/reduxToolKit/provider";
// import App from "./page";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Paradise store",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
        <Header />
        {/* <App /> */}
        {children}
        <Footer />
        </Providers>
      </body>
    </html>
  );
}
